name: packmol
owner: chemteam
description: "PACKMOL is a package for creating starting structures for Molecular Dynamics simulations"
homepage_url: http://m3g.iqm.unicamp.br/packmol/home.shtml
long_description: |
    "PACKMOL creates an initial point for molecular dynamics simulations by packing molecules in defined regions of space. The packing guarantees that short range repulsive interactions do not disrupt the simulations.
    The great variety of types of spatial constraints that can be attributed to the molecules, or atoms within the molecules, makes it easy to create ordered systems, such as lamellar, spherical or tubular lipid layers.
    The user must provide only the coordinates of one molecule of each type, the number of molecules of each type and the spatial constraints that each type of molecule must satisfy."
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem
type: unrestricted
categories:
- Molecular Dynamics
- Computational chemistry
